AWSTemplateFormatVersion: 2010-09-09
Description: Plantilla para la creacion de un Transit Gateway con 1 VPC de servicio y 2 VPCs cliente. El trafico de las VPC cliente se realiza de forma privada a traves de los Gateway NAT de la VPC de servicio. No es posible la comunicacion entre las VPCs cliente. Ademas, lanza tres instancias en cada una de las VPCs en subredes privadas con un perfil de instancia que permita registrarse con AWS SSM
Parameters:
  ASN:
    Type: Number
    Default: 64512
    MinValue: 64512
    MaxValue: 65534
  AmiID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: ID de la AMI
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2'
  CIDRVPCServicio:
    Type: String
    Description: Bloque CIDR de la VPC de Servicio
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Default: 10.0.0.0/16
    ConstraintDescription: Debe ser una red IP válida de la forma x.x.x.x
  CIDRVPCA:
    Type: String
    Description: Bloque CIDR de la VPC-A
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Default: 192.168.0.0/17
    ConstraintDescription: Debe ser una red IP válida de la forma x.x.x.x
  CIDRVPCB:
    Type: String
    Description: Bloque CIDR de la VPC-B
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Default: 192.168.128.0/17
    ConstraintDescription: Debe ser una red IP válida de la forma x.x.x.x
  EntornoLearnerLab:
    Type: String
    Description: Indica si se despliega la pila en AWS Learner Labs o en una cuenta convencional de AWS
    AllowedValues: ["SI","NO"]
    Default: "NO"
Conditions:
  CrearRolIAM: !Equals [!Ref EntornoLearnerLab, "NO"]
Resources:
  miTransitGateway:
    Type: 'AWS::EC2::TransitGateway'
    Properties:
      AmazonSideAsn: !Ref ASN
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: disable
      Description: Mi Transit Gateway
      Tags:
        - Key: Name
          Value: Demo-Transit-Gateway
  VPCServicio:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Nombre: Servicio
        VPC: !Ref CIDRVPCServicio 
        AZ: 1
        SubredesPublicas: SI
        SubredesPrivadas: SI
        NATGateways: SI
        Bastion: 'NO'
        LearnerLab: !Ref EntornoLearnerLab
      TemplateURL: ./vpc.yaml
  VPCA:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Nombre: A
        VPC: !Ref CIDRVPCA 
        AZ: 1
        SubredesPublicas: 'NO'
        SubredesPrivadas: SI
        NATGateways: 'NO'
        Bastion: 'NO'
        LearnerLab: !Ref EntornoLearnerLab
      TemplateURL: ./vpc.yaml
  VPCB:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Nombre: B
        VPC: !Ref CIDRVPCB
        AZ: 1
        SubredesPublicas: 'NO'
        SubredesPrivadas: SI
        NATGateways: 'NO'
        Bastion: 'NO'
        LearnerLab: !Ref EntornoLearnerLab
      TemplateURL: ./vpc.yaml
  RutaTablaRutasPublicaVPCServicioVPCA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !GetAtt VPCServicio.Outputs.TablaRutasPublica
      DestinationCidrBlock: !Ref CIDRVPCA
      TransitGatewayId: !Ref miTransitGateway
    DependsOn: AsociacionVPCServicio
  RutaTablaRutasPrivada1VPCServicioVPCA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !GetAtt VPCServicio.Outputs.TablaRutasPrivada1
      DestinationCidrBlock: !Ref CIDRVPCA
      TransitGatewayId: !Ref miTransitGateway
    DependsOn: AsociacionVPCServicio
  RutaTablaRutasPublicaVPCServicioVPCB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !GetAtt VPCServicio.Outputs.TablaRutasPublica
      DestinationCidrBlock: !Ref CIDRVPCB
      TransitGatewayId: !Ref miTransitGateway
    DependsOn: AsociacionVPCServicio
  RutaTablaRutasPrivada1VPCServicioVPCB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !GetAtt VPCServicio.Outputs.TablaRutasPrivada1
      DestinationCidrBlock: !Ref CIDRVPCB
      TransitGatewayId: !Ref miTransitGateway
    DependsOn: AsociacionVPCServicio
  RutaTablaRutasPrivada1VPCATGW:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !GetAtt VPCA.Outputs.TablaRutasPrivada1
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: !Ref miTransitGateway
    DependsOn: AsociacionVPCA
  RutaTablaRutasPrivada1VPCBTGW:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !GetAtt VPCB.Outputs.TablaRutasPrivada1
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: !Ref miTransitGateway
    DependsOn: AsociacionVPCB
  AsociacionVPCServicio:
    Type: 'AWS::EC2::TransitGatewayAttachment'
    Properties:
      VpcId: !GetAtt VPCServicio.Outputs.VPC
      TransitGatewayId: !Ref miTransitGateway
      SubnetIds:
        - !GetAtt VPCServicio.Outputs.Privada1
      Tags:
        - Key: Name
          Value: AsociacionVPCServicio
  AsociacionVPCA:
    Type: 'AWS::EC2::TransitGatewayAttachment'
    Properties:
      VpcId: !GetAtt VPCA.Outputs.VPC
      TransitGatewayId: !Ref miTransitGateway
      SubnetIds:
        - !GetAtt VPCA.Outputs.Privada1
      Tags:
        - Key: Name
          Value: AsociacionVPCA
  AsociacionVPCB:
    Type: 'AWS::EC2::TransitGatewayAttachment'
    Properties:
      VpcId: !GetAtt VPCB.Outputs.VPC
      TransitGatewayId: !Ref miTransitGateway
      SubnetIds:
        - !GetAtt VPCB.Outputs.Privada1
      Tags:
        - Key: Name
          Value: AsociacionVPCB
  TablaRutasVPCServicio:
    Type: 'AWS::EC2::TransitGatewayRouteTable'
    Properties:
      TransitGatewayId: !Ref miTransitGateway
      Tags:
        - Key: Name
          Value: TablaRutasVPCServicio
  TablaRutasVPCCliente:
    Type: 'AWS::EC2::TransitGatewayRouteTable'
    Properties:
      TransitGatewayId: !Ref miTransitGateway
      Tags:
        - Key: Name
          Value: TablaRutasVPC-Cliente
  AsociacionTablaRutasVPCServicio:
    Type: 'AWS::EC2::TransitGatewayRouteTableAssociation'
    Properties:
      TransitGatewayAttachmentId: !Ref AsociacionVPCServicio
      TransitGatewayRouteTableId: !Ref TablaRutasVPCServicio
  AsociacionTablaRutasVPCA:
    Type: 'AWS::EC2::TransitGatewayRouteTableAssociation'
    Properties:
      TransitGatewayAttachmentId: !Ref AsociacionVPCA
      TransitGatewayRouteTableId: !Ref TablaRutasVPCCliente
  AsociacionTablaRutasVPCB:
    Type: 'AWS::EC2::TransitGatewayRouteTableAssociation'
    Properties:
      TransitGatewayAttachmentId: !Ref AsociacionVPCB
      TransitGatewayRouteTableId: !Ref TablaRutasVPCCliente
  RutaEstaticaClienteTraficoInternet:
    Type: 'AWS::EC2::TransitGatewayRoute'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayAttachmentId: !Ref AsociacionVPCServicio
      TransitGatewayRouteTableId: !Ref TablaRutasVPCCliente
  RutaEstaticaClienteARFC1918:
    Type: 'AWS::EC2::TransitGatewayRoute'
    Properties:
      DestinationCidrBlock: !Ref CIDRVPCA
      Blackhole: true
      TransitGatewayRouteTableId: !Ref TablaRutasVPCCliente
  RutaEstaticaClienteBRFC1918:
    Type: 'AWS::EC2::TransitGatewayRoute'
    Properties:
      DestinationCidrBlock: !Ref CIDRVPCB
      Blackhole: true
      TransitGatewayRouteTableId: !Ref TablaRutasVPCCliente
  RutaPropagadaVPCServicioVPCA:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties: 
      TransitGatewayAttachmentId: !Ref AsociacionVPCA
      TransitGatewayRouteTableId: !Ref TablaRutasVPCServicio
  RutaPropagadaVPCServicioVPCB:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties: 
      TransitGatewayAttachmentId: !Ref AsociacionVPCB
      TransitGatewayRouteTableId: !Ref TablaRutasVPCServicio
  RolInstanciasEC2:
    Type: AWS::IAM::Role
    Condition: CrearRolIAM
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  PerfilInstanciasEC2:
    Type: AWS::IAM::InstanceProfile
    Condition: CrearRolIAM
    Properties:
      Roles:
        - !Ref RolInstanciasEC2
  GrupoSeguridadICMPVPCServicio:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Trafico ICMP para instancias en VPC de servicio
      SecurityGroupIngress:
        - IpProtocol: icmp
          CidrIp: 0.0.0.0/0
          FromPort: -1
          ToPort: -1
      VpcId: !GetAtt VPCServicio.Outputs.VPC
  GrupoSeguridadICMPVPCA:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Trafico ICMP para instancias en VPC A
      SecurityGroupIngress:
        - IpProtocol: icmp
          CidrIp: 0.0.0.0/0
          FromPort: -1
          ToPort: -1
      VpcId: !GetAtt VPCA.Outputs.VPC
  GrupoSeguridadICMPVPCB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Trafico ICMP para instancias en VPC B
      SecurityGroupIngress:
        - IpProtocol: icmp
          CidrIp: 0.0.0.0/0
          FromPort: -1
          ToPort: -1
      VpcId: !GetAtt VPCB.Outputs.VPC
  InstanciaVPCA:
    Type: AWS::EC2::Instance
    DependsOn: RutaPropagadaVPCServicioVPCA
    Properties:
      ImageId: !Ref AmiID
      InstanceType: t4g.micro
      SubnetId: !GetAtt VPCA.Outputs.Privada1
      IamInstanceProfile: !If [CrearRolIAM, !Ref PerfilInstanciasEC2, LabInstanceProfile]
      SecurityGroupIds: [!Ref GrupoSeguridadICMPVPCA]
      Tags:
        - Key: Name
          Value: Instancia-VPC-A
  InstanciaVPCB:
    Type: AWS::EC2::Instance
    DependsOn: RutaPropagadaVPCServicioVPCB
    Properties:
      ImageId: !Ref AmiID
      InstanceType: t4g.micro
      SubnetId: !GetAtt VPCB.Outputs.Privada1
      IamInstanceProfile: !If [CrearRolIAM, !Ref PerfilInstanciasEC2, LabInstanceProfile]
      SecurityGroupIds: [!Ref GrupoSeguridadICMPVPCB]
      Tags:
        - Key: Name
          Value: Instancia-VPC-B
  InstanciaVPCServicio:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiID
      InstanceType: t4g.micro
      SubnetId: !GetAtt VPCServicio.Outputs.Privada1
      IamInstanceProfile: !If [CrearRolIAM, !Ref PerfilInstanciasEC2, LabInstanceProfile]
      SecurityGroupIds: [!Ref GrupoSeguridadICMPVPCServicio]
      Tags:
        - Key: Name
          Value: Instancia-VPC-Servicio
